config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :visits
    resources :categories
    resources :clients
    resources :doctors

    root to: 'clients#index'
  end

  devise_for :doctors
  devise_for :clients

  root 'main#home'

  resources :clients do
    resources :visits, only: %i[index show create delete new]
  end
  resources :doctors do
    resources :visits, only: %i[index show update edit]
  end

  resources :categories
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def home
    if client_signed_in?
      redirect_to client_path(current_client)
    elsif doctor_signed_in?
      redirect_to doctor_path(current_doctor)
    else
      root_path
    end
  end
end

app/views/main/home.html.erb
<div class="container-fluid d-flex align-items-center justify-content-center" style="min-height: 70vh;">
  <div class="row">
    <div class="col">
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Choose your role
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li class="dropdown-item"><%= link_to 'Doctor', new_doctor_registration_path, class: "nav-link" %></li>
          <li class="dropdown-item"><%= link_to 'Patient', new_client_registration_path, class: "nav-link" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>