config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :visits
    resources :categories
    resources :clients
    resources :doctors

    root to: 'clients#index'
  end

  devise_for :doctors
  devise_for :clients

  root 'main#home'

  resources :clients do
    resources :visits, only: %i[index show create delete new]
  end
  resources :doctors do
    resources :visits, only: %i[index show update edit]
  end

  resources :categories
end

app/views/shared/_flash_msg.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= bootstrap_class_for(key) %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрити"></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32">
        <use xlink:href="#bootstrap"></use>
      </svg>
      <span class="fs-4">Hospital Control</span>
    </a>
    <a>
      <% if current_client.present? %>
        <%= button_to('Log Out', destroy_client_session_path, method: :delete) %>
      <% elsif current_doctor.present? %>
        <%= button_to('Log Out', destroy_doctor_session_path, method: :delete) %>
      <% else %>
        <%= button_to 'Home', destroy_client_session_path, method: :delete %>
      <% end %>
    </a>
  </header>
</div>

app/views/shared/_pagi.html.erb
<nav aria-label="...">
  <ul class="pagination">
    <% if pages.current_page == 1 %>
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Previous</a>
      </li>
    <% else %>
      <li class="page-item">
        <a class="page-link" href="<%= url_for(page: pages.current_page - 1) %>">Previous</a>
      </li>
    <% end %>

    <% pages.total_pages.times do |page| %>
      <% if page + 1 == pages.current_page %>
        <li class="page-item active">
          <a class="page-link" href="#"><%= page + 1 %> <span class="sr-only"></span></a>
        </li>
      <% else %>
        <li class="page-item">
          <a class="page-link" href="<%= url_for(page: page + 1) %>"><%= page + 1 %></a>
        </li>
      <% end %>
    <% end %>

    <% if pages.current_page == pages.total_pages %>
      <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
      </li>
    <% else %>
      <li class="page-item">
        <a class="page-link" href="<%= url_for(page: pages.current_page + 1) %>">Next</a>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32">
      <use xlink:href="#bootstrap"></use>
    </svg>
    <span class="fs-4">Menu</span>
  </a>
  <hr>
  <% if current_client.present? %>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
          <%= link_to client_path(current_client), class: "nav-link #{'active' if current_page?(client_path(current_client))}", "aria-current": "page" do %>
          <svg class="bi me-2" width="16" height="16">
            <use xlink:href="#home"></use>
          </svg>
          Your profile
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to client_visits_path(current_client), class: "nav-link #{'active' if current_page?(client_visits_path(current_client))}", "aria-current": "page" do %>
          <svg class="bi me-2" width="16" height="16">
            <use xlink:href="#home"></use>
          </svg>
          Your visits
        <% end %>
      </li>
      <li>
        <%= link_to doctors_path, class: "nav-link #{'active' if current_page?(doctors_path)}", "aria-current": "page" do %>
          <svg class="bi me-2" width="16" height="16">
            <use xlink:href="#table"></use>
          </svg>
          Doctors
        <% end %>
      </li>
      <li>
        <%= link_to new_client_visit_path(client_id: current_client.id), class: "nav-link #{'active' if current_page?(new_client_visit_path(client_id: current_client.id))}", "aria-current": "page" do %>
          <svg class="bi me-2" width="16" height="16">
            <use xlink:href="#table"></use>
          </svg>
          Create visit
        <% end %>
      </li>
    </ul>
  <% else %>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to doctor_path(current_doctor), class: "nav-link #{'active' if current_page?(doctor_path(current_doctor))}", "aria-current": "page" do %>
          <svg class="bi me-2" width="16" height="16">
            <use xlink:href="#home"></use>
          </svg>
          Your profile
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to doctor_visits_path(current_doctor), class: "nav-link #{'active' if current_page?(doctor_visits_path(current_doctor))}", "aria-current": "page" do %>
          <svg class="bi me-2" width="16" height="16">
            <use xlink:href="#home"></use>
          </svg>
          Your visits
        <% end %>
      </li>
    </ul>
  <% end %>
  <hr>
</div>